import axios from 'axios';

/**
 * Movyra API Client
 * Configured Axios instance to communicate with the Rust (Axum) Backend.
 */
const api = axios.create({
  baseURL: import.meta.env.VITE_API_URL || 'http://localhost:8080/api',
  headers: {
    'Content-Type': 'application/json',
  },
});

// Request Interceptor: Automatically attach the JWT token to every request
api.interceptors.request.use(
  (config) => {
    // Retrieve the internal JWT token generated by the Rust backend
    const token = localStorage.getItem('movyra_jwt');
    
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    
    return config;
  },
  (error) => {
    return Promise.reject(error);
  }
);

// Response Interceptor: Global error handling (e.g., Token Expiration)
api.interceptors.response.use(
  (response) => {
    return response;
  },
  (error) => {
    // If the Rust backend rejects the token (401 Unauthorized)
    if (error.response && error.response.status === 401) {
      // Clear compromised/expired credentials
      localStorage.removeItem('movyra_jwt');
      localStorage.removeItem('movyra_user');
      
      // Force redirect to login screen for re-authentication
      if (window.location.pathname !== '/auth-login' && window.location.pathname !== '/auth-signup') {
        window.location.href = '/auth-login';
      }
    }
    
    return Promise.reject(error);
  }
);

export default api;